# VanillaOpenAIFramework:
#   - task: "ner"
#     n_runs: 10
#     init_kwargs:
#       prompt: "Extract and resolve a list of entities from the following text: {text}"
#       llm_model: "gpt-4o-mini-2024-07-18"
#       llm_model_family: "openai"
#       source_data_pickle_path: "data/ner.pkl"

VanillaGoogleFramework:
  - task: "ner"
    n_runs: 1
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "gemini-2.0-flash"
      llm_model_family: "google"
      source_data_pickle_path: "data/ner.pkl"
      api_delay_seconds: 5

VanillaOllamaFramework:
  - task: "ner"
    n_runs: 1
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "gemma3:12b-it-qat"
      llm_model_family: "ollama"
      source_data_pickle_path: "data/ner.pkl"
      host: "http://localhost:11434"